window.STUDY={lessons:[
{id:'visao',group:'Fundamentos',title:'O problema e o objetivo do SAE',source:'pages/dashboard.php · pages/estoque.php · pages/qr_codes.php',body:[
'O Sistema de Alimentação Escolar organiza instituições, alunos, refeições e alimentos. A proposta é reunir registros que poderiam estar espalhados entre listas, anotações e planilhas, permitindo consultas por instituição. O cadastro e o login abrem o acesso a indicadores, QR Codes, estoque, horários, turnos e relatórios.',
'Refeição é um atendimento ao aluno; estoque é a quantidade disponível de um produto; cardápio reúne produtos. Esses conceitos se relacionam, mas não são sinônimos. O QR Code registra uma refeição; o cardápio desconta ingredientes em outro fluxo. Há também uma área administrativa e uma API Node.js separada.',
'Diferencie objetivo de resultado medido. O código demonstra centralização e consultas, mas não contém uma avaliação que comprove uma porcentagem de redução de desperdício ou aumento de produtividade. Apresente esses resultados como benefícios esperados, caso ainda não tenham sido medidos.'
],say:'Meu projeto centraliza registros da alimentação escolar, organizando os dados por instituição e transformando ações em registros e consultas.',question:'O que não posso afirmar sem uma avaliação?',answer:'Uma redução percentual de desperdício ou ganho de produtividade. O código implementa recursos; o impacto exige medição.'},
{id:'arquitetura',group:'Fundamentos',title:'Arquitetura: navegador, PHP, API e banco',source:'config/bootstrap.php · server.js · config/database.js',body:[
'O caminho principal das telas usa PHP. O navegador faz uma requisição HTTP; o servidor executa o arquivo PHP, consulta o banco quando necessário e devolve HTML, JSON ou texto. O navegador recebe o resultado, não o código PHP executado. JavaScript complementa a tela com eventos, modais e fetch.',
'bootstrap.php carrega configurações, rotas, constantes, conexão, funções, autenticação e e-mail. Isso centraliza a inicialização, mas os arquivos ainda misturam apresentação e regras. É mais preciso descrever uma aplicação organizada por pastas e responsabilidades do que afirmar que existe um framework MVC completo.',
'server.js define outra aplicação: Express na porta 3000, com /api/auth, /api/alunos, /api/refeicoes e /api/historico. Ela devolve JSON e usa mysql2 e JWT. As telas PHP analisadas chamam principalmente endpoints PHP; a existência da API no repositório não prova que ela seja o backend de todas as telas.',
'As duas implementações acessam o mesmo nome de banco, mas têm conexões e autenticações distintas. Sessão PHP não é JWT. Iniciar Apache/PHP não inicia automaticamente Node.js; server.js precisa de processo próprio.'
],code:'Navegador → Apache/PHP → mysqli → MySQL/MariaDB\nCliente de API → Express → mysql2 → MySQL/MariaDB\nPHP: sessão no servidor | API: token Bearer',say:'Há uma aplicação web PHP e uma API Express separada. Elas compartilham o domínio e o banco, mas têm caminhos próprios.',question:'A API Node.js processa automaticamente todas as telas?',answer:'Não. As telas principais executam PHP; a API Express é um caminho separado em JSON.'},
{id:'linguagens',group:'Fundamentos',title:'A função de cada linguagem e biblioteca',source:'index.php · assets/ · package.json · src/PHPMailer.php',body:[
'HTML é linguagem de marcação: estrutura títulos, formulários, tabelas e botões. CSS descreve apresentação, espaçamento, cores, responsividade e estados visuais. JavaScript é linguagem de programação: reage a eventos, manipula o DOM e envia requisições. No Node.js, JavaScript também executa no servidor.',
'PHP implementa regras do servidor e gera respostas. SQL é a linguagem usada para definir e manipular dados. MySQL ou MariaDB é o sistema gerenciador de banco de dados; mysqli é a extensão PHP de conexão. SQL, SGBD e biblioteca de conexão são conceitos diferentes.',
'PHPMailer monta e envia e-mails por SMTP. Lucide fornece ícones SVG, incluídos localmente na última versão. jsQR lê códigos em imagens da câmera e QRCode gera sua representação visual. bcryptjs compara hashes na API, jsonwebtoken assina/verifica JWT, dotenv carrega variáveis e mysql2 oferece pool de conexões.',
'Uma dependência declarada não prova uso efetivo. cors está no package.json, mas server.js não mostra app.use(cors()). O script npm test apenas informa que não há teste configurado. Não apresente esses itens como funcionalidades completas.'
],say:'PHP processa o servidor, SQL trabalha com os dados, HTML estrutura a tela, CSS apresenta e JavaScript cria as interações.',question:'Qual a diferença entre SQL, MySQL e mysqli?',answer:'SQL é linguagem, MySQL é SGBD e mysqli é a extensão de conexão do PHP.'},
{id:'php',group:'Fundamentos',title:'Como ler o PHP do projeto',source:'auth/salvar_estoque.php · config/funcoes.php',body:[
'Variáveis começam com $. $_POST reúne campos enviados no corpo do formulário; $_GET reúne parâmetros da URL; $_SESSION guarda estado associado à sessão. O operador ?? define um valor padrão se uma chave estiver ausente ou nula. Casts como (int) convertem dados, mas não substituem validações de domínio.',
'declare(strict_types=1) influencia verificações em chamadas de funções tipadas; não valida automaticamente formulários. O projeto combina trim, filter_var, casts e condições de faixa. required e min no HTML ajudam o usuário, mas a requisição pode ser enviada fora da interface, então o servidor deve validar novamente.',
'require_once inclui um arquivo uma vez por execução. header define cabeçalhos e redirecionamentos; exit interrompe o processamento. $conn->prepare e $stmt->execute são chamadas de métodos. fetch_assoc retorna uma linha associativa e fetch_all retorna várias.',
'try/catch trata falhas e permite rollback. htmlspecialchars escapa caracteres para uma saída HTML; não é parametrização de SQL. json_encode serializa dados para JSON; FormData é uma estrutura do navegador, não uma tabela do banco.'
],code:"$id = (int) ($_POST['id'] ?? 0);\n$valor = filter_var($_POST['quantidade'] ?? '', FILTER_VALIDATE_FLOAT);\nif ($id <= 0 || $valor === false || $valor <= 0) {\n    http_response_code(400);\n    exit('Dados inválidos.');\n}",say:'A validação do servidor é obrigatória mesmo quando o navegador já valida os campos.',question:'required no HTML garante uma entrada segura?',answer:'Não. O servidor deve repetir validações e verificar autorização.'},
{id:'relacional',group:'Banco de dados',title:'Modelo relacional e as 13 tabelas',source:'banco/tabelas/*.php · banco/migrar_integracao.php',body:[
'Tabela representa um conjunto de registros de uma entidade ou relação. Linha é uma ocorrência; coluna é um atributo. alunos descreve pessoas e refeicoes descreve eventos. O evento aponta para aluno_id, evitando repetir todos os dados cadastrais do aluno a cada atendimento.',
'O instalador inclui 12 definições: instituicoes, administradores, usuarios, alunos, turnos, horarios, cardapios, estoque, configuracoes_estoque, refeicoes, historico e consumo. A migração cria cardapio_itens: o modelo composto passa a ter 13 tabelas.',
'instituicoes centraliza o escopo institucional. administradores não tem instituicao_id na definição inicial e representa outra identidade. usuarios tem vínculo institucional, mas não é a tabela usada pelo login institucional PHP; esse login consulta instituicoes.',
'Este atlas representa scripts de criação mais migração, não o estado certificado de qualquer instalação. CREATE TABLE IF NOT EXISTS não atualiza uma tabela existente. Verifique SHOW CREATE TABLE e SHOW COLUMNS antes de demonstrar uma base antiga.'
],say:'Separei entidades e eventos, relacionando registros por identificadores. O atlas mostra o esquema inicial acrescido da migração.',question:'Por que 13 tabelas se o instalador cria 12?',answer:'cardapio_itens é criada pela migração de integração.'},
{id:'chaves',group:'Banco de dados',title:'PK, FK, UNIQUE e cardinalidades',source:'banco/tabelas/alunos.php · banco/tabelas/configuracoes_estoque.php · banco/migrar_integracao.php',body:[
'PRIMARY KEY identifica uma linha de forma única e não nula. O projeto usa id inteiro AUTO_INCREMENT. Essa identidade técnica não representa permissão: saber um ID não autoriza acesso. FOREIGN KEY exige que uma referência não nula aponte para uma linha válida da tabela de destino.',
'Instituição para alunos é 1:N: a instituição pode ter zero ou muitos alunos, e cada aluno tem uma instituição obrigatória. A FK fica no lado muitos. configuracoes_estoque possui UNIQUE(instituicao_id): uma instituição pode ter zero ou uma configuração, não necessariamente exatamente uma.',
'Cardápios e produtos têm relação N:N resolvida por cardapio_itens. A associação guarda cardapio_id, estoque_id e quantidade. A quantidade é característica do uso daquele produto naquele cardápio. A migração não declara UNIQUE(cardapio_id, estoque_id); o PHP agrega itens repetidos antes de gravar.',
'UNIQUE(instituicao_id, codigo) impede repetir um código preenchido na mesma instituição; o mesmo código pode existir em outra. Como codigo aceita NULL, unicidade não é sinônimo de preenchimento obrigatório. Chave composta usa mais de uma coluna para definir uma restrição.'
],code:'instituicoes 1 ── 0..N alunos\nalunos       1 ── 0..N refeicoes\ninstituicoes 1 ── 0..1 configuracoes_estoque\ncardapios    1 ── 0..N cardapio_itens N..0 ── 1 estoque',say:'A FK garante a referência; a cardinalidade explica quantas ocorrências podem se relacionar.',question:'Por que existe cardapio_itens?',answer:'Resolve N:N entre cardápios e produtos e guarda a quantidade de cada produto em cada cardápio.'},
{id:'tipos',group:'Banco de dados',title:'Tipos de dados, NULL e DEFAULT',source:'banco/tabelas/estoque.php · banco/tabelas/historico.php · banco/tabelas/horarios.php',body:[
'INT guarda inteiros. DECIMAL(10,2) tem dez dígitos totais, sendo dois decimais: o maior valor positivo é 99.999.999,99. É adequado para quantidades fracionadas e preços porque representa decimais exatos no banco. FLOAT usa aproximações binárias; os valores recebidos pelo PHP ainda precisam de validação e arredondamento apropriado.',
'VARCHAR(n) é texto de tamanho variável limitado. Telefone e código são texto porque podem conter símbolos ou zeros iniciais. TEXT serve para descrições longas. horario é VARCHAR(5) no projeto; PHP valida HH:MM. TIME seria uma alternativa futura, não o tipo atual.',
'DATE guarda data; DATETIME guarda data e hora; TIMESTAMP aparece em criação e atualização. token_expira é DATETIME. Relógios e fusos da aplicação e do banco precisam estar alinhados. NULL significa ausência de valor, não zero ou string vazia; compare com IS NULL, não = NULL.',
'DEFAULT vale quando a coluna é omitida ou quando se pede o padrão; não substitui um 0 enviado explicitamente. Antes da correção, PHP enviava ativo=0, então DEFAULT TRUE não era usado. BOOLEAN é sinônimo de TINYINT(1) em MySQL/MariaDB, não uma restrição automática a só 0 e 1.',
'JSON guarda snapshots no histórico; sua implementação interna difere entre MySQL e MariaDB. InnoDB é a engine declarada, com transações e FKs. utf8mb4 é o conjunto de caracteres; utf8mb4_unicode_ci define comparação textual sem distinção de maiúsculas conforme a collation.'
],say:'Escolhi tipos pelo domínio: DECIMAL para frações, texto para códigos e datas próprias para eventos. Padrões não corrigem valores explícitos errados.',question:'Por que DEFAULT TRUE não corrigia produtos inativos?',answer:'O PHP enviava ativo=0 explicitamente; o valor padrão não substitui esse valor.'},
{id:'normalizacao',group:'Banco de dados',title:'Normalização e dependências funcionais',source:'banco/tabelas/alunos.php · banco/tabelas/refeicoes.php · banco/migrar_integracao.php',body:[
'Normalização reduz redundâncias que causam anomalias de inserção, alteração e exclusão. Se toda refeição repetisse telefone e responsável, uma correção cadastral exigiria mudar muitas linhas. Separar alunos e referenciar aluno_id evita essa repetição.',
'A primeira forma normal evita grupos repetitivos e listas em uma célula. cardapio_itens representa um produto por linha em vez de uma coluna com uma lista de alimentos. A segunda forma normal elimina dependências de apenas parte de uma chave candidata composta. A terceira evita dependências transitivas entre atributos não-chave.',
'Ter um id não prova 3FN. É preciso conhecer as dependências funcionais: quais atributos determinam quais outros. instituicao_id em refeicoes facilita filtragem, mas pode ser determinado pelo aluno; essa redundância precisa de verificação de consistência.',
'tipo e horario textuais em refeicoes coexistem com IDs adicionados pela migração. Podem servir como snapshot do evento, mas a intenção deve ser documentada. Não afirme normalização perfeita sem analisar o domínio. JSON no histórico é um snapshot de auditoria, não substituto geral dos relacionamentos operacionais.'
],say:'A separação das entidades reduz repetição. Ainda preciso justificar redundâncias e snapshots antes de afirmar uma forma normal para todo o esquema.',question:'A presença de uma PK id prova terceira forma normal?',answer:'Não. A normalização depende das dependências funcionais e regras do domínio.'},
{id:'integridade',group:'Banco de dados',title:'Integridade e efeitos da exclusão',source:'banco/tabelas/consumo.php · banco/tabelas/historico.php · banco/migrar_integracao.php',body:[
'Integridade de entidade exige identidades válidas; referencial exige referências válidas; domínio envolve valores permitidos. Não há CHECK de saldo não negativo no esquema de estoque apresentado: os endpoints fazem esse controle. Uma tabela válida estruturalmente não garante todas as regras do negócio.',
'ON DELETE CASCADE exclui dependentes. Instituição para alunos e aluno para refeições usam essa ação. UPDATE ativo=0 é desativação, preserva a linha e não dispara cascata de exclusão. Essa diferença é essencial para discutir preservação de histórico.',
'ON DELETE SET NULL conserva o dependente e limpa a referência. Aparece em consumo.item_estoque_id, historico.usuario_id e cardapios.turno_id. A coluna deve aceitar NULL. cardapio_itens.estoque_id não declara cascata; a exclusão de produto referenciado é restringida em InnoDB.',
'Uma FK para aluno e outra para instituição não garante que esse aluno pertence a essa instituição. O fluxo consulta o aluno já com instituicao_id. Uma melhoria possível é modelar uma restrição composta adequada, além da validação do servidor.',
'horario_id e turno_id em refeicoes são INT NULL adicionados sem FOREIGN KEY pela migração. São relações lógicas validadas pelo aplicativo, mas não têm aquela proteção estrutural no script. O atlas separa essas relações das FKs declaradas.'
],say:'Existência da referência e autorização são regras diferentes. Desativar também é diferente de excluir e disparar cascatas.',question:'A FK de aluno_id impede uma refeição da instituição errada?',answer:'Sozinha, não. É necessário validar que o aluno pertence à instituição da operação.'},
{id:'sql',group:'Banco de dados',title:'SQL: CRUD e consultas preparadas',source:'auth/salvar_estoque.php · pages/relatorios.php',body:[
'CREATE TABLE e ALTER TABLE definem estrutura. INSERT cria registros, SELECT consulta, UPDATE altera e DELETE remove. O Create de CRUD normalmente corresponde a INSERT, não a CREATE TABLE. WHERE seleciona linhas; ORDER BY ordena; LIMIT restringe a saída.',
'id identifica o produto e instituicao_id restringe a operação à conta. Um UPDATE sem WHERE pode afetar todas as linhas. Sem ORDER BY, não há garantia da ordem desejada. Nomear colunas é mais claro e reduz exposição desnecessária em comparação com SELECT *.',
'Prepared statements separam SQL e valores: prepare recebe placeholders ?, bind_param vincula tipos/variáveis e execute executa. i representa inteiro, d número passado pelo PHP e s string. O d da ligação não altera o tipo DECIMAL da coluna no banco.',
'Parametrização ajuda contra injeção SQL por valores, mas não implementa autorização, não escapa HTML e não substitui validação. Identificadores dinâmicos como nome de tabela não são parametrizados da mesma maneira; devem vir de uma lista permitida quando necessários.'
],code:"$stmt = $conn->prepare(\n 'SELECT item, quantidade FROM estoque\n  WHERE id = ? AND instituicao_id = ?'\n);\n$stmt->bind_param('ii', $id, $instituicaoId);\n$stmt->execute();",say:'Os valores são vinculados separadamente ao SQL. Mesmo assim, mantenho o filtro institucional para autorização.',question:'Uma consulta preparada autoriza acesso a qualquer ID?',answer:'Não. Ela separa valores do SQL; autorização depende de identidade e escopo.'},
{id:'joins',group:'Banco de dados',title:'JOIN, COUNT, SUM e relatórios',source:'pages/relatorios.php · pages/dashboard.php · pages/contar_consumo.php',body:[
'JOIN associa linhas relacionadas. O relatório combina refeicoes r e alunos a por r.aluno_id=a.id para exibir nome e turma. Os aliases tornam a consulta legível. INNER JOIN devolve correspondências; LEFT JOIN preserva todas as linhas à esquerda, mesmo sem uma correspondência.',
'Para procurar alunos sem refeição, parta de alunos com LEFT JOIN e use r.id IS NULL, posicionando filtros de data sem eliminar indevidamente linhas nulas. GROUP BY agrupa para agregação; WHERE filtra antes dela e HAVING filtra grupos.',
'COUNT(*) conta linhas; SUM(quantidade) soma valores. Uma linha com quantidade=3 conta uma linha e soma três. O dashboard soma quantidades do dia por tipo; contar_consumo conta linhas e o relatório usa count($registros). Essas métricas podem divergir.',
'O relatório filtra instituição, intervalo e aluno opcional, ordena por data/horário e aplica LIMIT 1000. Seus indicadores são calculados sobre as linhas carregadas, portanto podem não representar um intervalo com mais de mil registros. O arquivo assets/js/relatorios.js contém números demonstrativos; não é evidência de cálculo real em banco.'
],code:'SELECT a.nome, SUM(r.quantidade) AS total\nFROM refeicoes r\nJOIN alunos a ON a.id = r.aluno_id\nWHERE r.instituicao_id = ?\nGROUP BY a.id, a.nome\nORDER BY total DESC;',say:'O JOIN recupera informações relacionadas; a agregação resume eventos. Primeiro defino se a métrica conta linhas ou unidades.',question:'COUNT(*) e SUM(quantidade) são sempre iguais?',answer:'Não. COUNT conta linhas e SUM soma os valores da coluna.'},
{id:'indices',group:'Banco de dados',title:'Índices e desempenho',source:'banco/tabelas/refeicoes.php · banco/tabelas/alunos.php',body:[
'Índice é uma estrutura auxiliar que pode acelerar consultas e ordenações. PK e UNIQUE têm índices associados. Há índices de data, tipo, turma e e-mail nos scripts. Eles consomem espaço e aumentam o trabalho necessário nas escritas.',
'Consultas combinam frequentemente instituicao_id e data_refeicao. Um índice composto nessa ordem é candidato de melhoria, não garantia de ganho. Deve ser avaliado com volume representativo e EXPLAIN, observando plano, linhas examinadas e tempo.',
'A ordem de um índice composto importa: (instituicao_id, data_refeicao) atende o prefixo institucional e a combinação. Não é equivalente a um índice começando pela data em todos os cenários. Evite indexar indiscriminadamente todas as colunas.',
'LIMIT limita a saída, não garante que só aquela quantidade de linhas seja examinada. Uma base pequena não comprova escalabilidade. Na defesa, apresente uma hipótese de otimização e como mediria antes e depois.'
],code:'-- Proposta de melhoria, não migração aplicada:\nCREATE INDEX idx_refeicoes_instituicao_data\nON refeicoes (instituicao_id, data_refeicao);\n\nEXPLAIN SELECT * FROM refeicoes\nWHERE instituicao_id = 1;',say:'Escolho índices pelas consultas reais e verifico o plano antes de prometer desempenho.',question:'Por que não indexar tudo?',answer:'Índices usam espaço e encarecem escritas; devem atender padrões de consulta.'},
{id:'transacoes',group:'Banco de dados',title:'Transações, ACID e concorrência',source:'pages/salvar_cardapio.php · pages/registrar_consumo.php',body:[
'Transação agrupa alterações que devem ser confirmadas juntas. No cardápio: inserir cabeçalho, inserir itens, descontar estoque e registrar histórico. begin_transaction inicia, commit confirma e rollback desfaz o que ainda não foi confirmado diante de uma falha.',
'ACID: atomicidade é tudo ou nada; consistência preserva regras; isolamento controla a interação entre operações concorrentes; durabilidade preserva confirmações conforme as garantias do SGBD. Transações não criam regras que não existem: constraints e validações continuam necessárias.',
'O cardápio soma produtos repetidos, ordena IDs com ksort e usa SELECT ... FOR UPDATE dentro da transação. Bloquear as linhas evita uma janela desprotegida entre ler saldo e descontar. A ordem consistente ajuda a reduzir disputas, mas não prova ausência de deadlocks em todo cenário.',
'A baixa manual faz um único UPDATE com quantidade>=valor. Condição e subtração fazem parte da mesma instrução; affected_rows=0 indica que nenhuma linha cumpriu todas as condições. Já no cardápio, várias instruções precisam de uma unidade transacional.',
'PHP registra refeição e histórico em transação. Muitas rotas Node alteram o registro e depois inserem histórico sem transação explícita; a primeira alteração pode persistir se a segunda falhar. Não afirme que todos os caminhos do repositório têm a mesma garantia.'
],code:'BEGIN;\nSELECT quantidade FROM estoque\nWHERE id = ? AND instituicao_id = ? AND ativo = 1\nFOR UPDATE;\n-- validar; criar cardápio/itens; atualizar saldo; registrar histórico\nCOMMIT;\n-- falha antes de confirmar: ROLLBACK',say:'Cardápio e baixa de seus ingredientes formam uma unidade. Transações e bloqueios protegem essa unidade.',question:'E se um item do cardápio não tiver saldo?',answer:'O fluxo executa rollback e não confirma um cardápio parcial.'},
{id:'estoque',group:'Fluxos & segurança',title:'Cadastro, status, entrada e baixa',source:'auth/salvar_estoque.php · pages/estoque.php',body:[
'O cadastro recebe item, unidade, quantidade e estoque mínimo. Nome e unidade não podem ficar vazios; unidade tem limite de 50 caracteres; quantidade e mínimo são números não negativos. Novo produto recebe ativo=1 mesmo sem o campo no formulário. Na edição, o campo continua controlando status.',
'Alternar status usa UPDATE ativo=NOT ativo por id e instituição. A página principal filtra ativo=1, enquanto Configurações permite administrar os inativos. Desativação não apaga saldo nem linha. A entrada adiciona uma quantidade positiva a um produto ativo da instituição.',
'A baixa manual exige senha. O servidor busca o hash da instituição da sessão e usa password_verify antes de subtrair. O produto deve ser ativo, pertencer à instituição e ter quantidade suficiente. affected_rows verifica o efeito; a senha é limpa no formulário após a tentativa e ao fechar o modal.',
'A reautenticação foi acrescentada à baixa manual. Salvar cardápio também desconta ingredientes, mas esse fluxo separado não exige a senha novamente. A baixa manual também não registra movimento no histórico nesse endpoint. São limites reais da versão atual.'
],code:'UPDATE estoque\nSET quantidade = quantidade - ?\nWHERE id = ? AND instituicao_id = ?\n  AND ativo = 1 AND quantidade >= ?;',say:'Produto novo nasce ativo e a baixa manual combina reautenticação e atualização condicionada ao saldo.',question:'Toda redução de estoque exige senha?',answer:'Não. A baixa manual exige; a redução pelo salvamento de cardápio é outro fluxo sem essa reautenticação.'},
{id:'identidade',group:'Fluxos & segurança',title:'Cadastro institucional e sessão',source:'auth/salvar_cadastro.php · auth/login.php · admin/autenticar.php',body:[
'O cadastro grava nome, e-mail e hash em instituicoes. O login consulta o e-mail e verifica password_verify. No sucesso, session_regenerate_id(true) troca o identificador da sessão e são salvos ID, nome e e-mail. A senha não precisa ser guardada na sessão.',
'Autenticação responde quem está conectado; autorização responde o que essa identidade pode fazer. instituicao_id identifica o escopo, e WHERE instituicao_id=? limita operações. Um identificador de sessão no navegador referencia o estado no servidor.',
'Antes da correção, salvar_cadastro.php escolhia edição pela simples existência de sessão. Um cadastro com sessão podia sobrescrever nome/e-mail da conta antiga sem trocar sua senha. Agora cadastro envia acao=cadastrar e perfil envia acao=editar_perfil; a edição exige a ação explícita.',
'A área administrativa usa admin_id e administradores. nivel vem da migração. Existe um acesso fixo de desenvolvimento no arquivo de autenticação que precisa ser removido antes de uso real; seus valores não são reproduzidos neste site. Algumas rotas admin também usam IDs sem filtro institucional ou fallback de instituição: isolamento completo não está garantido em todo esse caminho.'
],say:'A sessão identifica a conta; a ação explícita diferencia cadastrar de editar. Isso evita sobrescrever o perfil ao tentar criar outra instituição.',question:'Por que um cadastro podia alterar a conta anterior?',answer:'O endpoint confundia uma sessão aberta com a intenção de editar o perfil.'},
{id:'recuperacao',group:'Fluxos & segurança',title:'Hash, token e recuperação de senha',source:'auth/enviar_recuperacao.php · auth/salvar_nova_senha.php · config/email.php',body:[
'Hash é uma transformação de sentido único, não criptografia reversível. password_hash gerencia algoritmo e salt; password_verify confere a entrada. A API usa bcryptjs: compatibilidade entre as camadas depende do formato/algoritmo, e PASSWORD_DEFAULT pode evoluir.',
'Recuperação gera random_bytes(32), converte com bin2hex em 64 caracteres e salva token_recuperacao e token_expira com validade de cinco minutos. O e-mail leva o token no link. O endpoint de troca verifica token e expiração, compara senha/confirmar_senha e exige ao menos oito bytes com strlen.',
'Depois da troca, o novo hash é salvo e token/expiração são limpos. O token atual é armazenado em texto; guardar só seu hash, limitar tentativas e garantir consumo atômico sob concorrência seriam melhorias. O fuso usado na geração e a comparação com NOW() precisam estar alinhados.',
'PHPMailer usa SMTP Gmail, STARTTLS e porta 587. Erro 535 é rejeição das credenciais do remetente, não da senha institucional. A configuração corrigida não imprime diálogo SMTP nem desabilita validação TLS. O link ainda usa localhost: aberto em outro dispositivo, ele aponta para aquele próprio dispositivo e precisa de uma URL de implantação adequada.'
],say:'O link usa um token aleatório temporário. A nova senha é salva como hash; a conta SMTP é a do remetente do sistema.',question:'Erro SMTP 535 indica senha institucional errada?',answer:'Não. O servidor de e-mail recusou as credenciais SMTP do remetente.'},
{id:'qr',group:'Fluxos & segurança',title:'QR Code e registro de refeições',source:'pages/qr_codes.php · pages/registrar_consumo.php · pages/get_aluno.php',body:[
'QR Code codifica uma informação para leitura visual. No atendimento, identifica o aluno; não autentica o operador nem prova identidade forte do portador. A câmera precisa de permissão e normalmente de HTTPS ou localhost. jsQR extrai o texto da imagem.',
'registrar_consumo.php exige POST, sessão, código, turno e horário. Busca aluno ativo por código e instituição. Confere turno e horário ativos dentro da mesma instituição. A identidade autorizadora vem da sessão, não do QR.',
'Apesar do nome do arquivo, esse fluxo grava em refeicoes e historico numa transação. Não grava na tabela consumo nem baixa ingrediente diretamente. consumo é uma tabela prevista para vincular aluno e item de estoque, mas não é a tabela usada por esse endpoint.',
'O endpoint não verifica uma refeição anterior e o esquema não define uma restrição única por aluno/turno/dia. Bloquear repetição na interface não garante ausência de duplicidade sob concorrência. As rotinas de CSV/QR em JavaScript também não provam persistência: gerar um código visual ou ler arquivo não equivale a executar INSERT no banco.'
],say:'QR acelera a identificação; o servidor valida escopo, turno e horário e registra a refeição.',question:'registrar_consumo.php escreve em consumo?',answer:'No fluxo analisado, escreve em refeicoes e historico.'},
{id:'api',group:'Fluxos & segurança',title:'API Node.js e JWT',source:'server.js · routes/ · middleware/auth.js',body:[
'Express define os endpoints. POST /api/auth/login consulta a instituição, compara hash e devolve JWT. O middleware exige Authorization: Bearer, verifica assinatura com JWT_SECRET e cria req.usuario. A expiração padrão é 8h quando JWT_EXPIRES_IN não foi configurado.',
'Alunos e refeições têm GET de coleção, GET por ID, POST, PUT e DELETE. Histórico tem listagem. req.usuario.id define a instituição. mysql2 usa pool e a interface de promises permite await; múltiplas instruções de uma transação devem usar a mesma conexão.',
'JWT assinado não é payload secreto. A assinatura detecta alteração, mas o conteúdo normalmente é legível. Token exige proteção de transporte e estratégia de expiração/revogação. A sessão PHP e o JWT da API não são intercambiáveis automaticamente.',
'A API insere snapshots no histórico, muitas vezes com usuario_id=null. Nem toda alteração e histórico têm transação explícita. A validação da API não é idêntica à do scanner PHP. O arquivo package.json não oferece uma suíte funcional em npm test; testes pontuais das correções não equivalem à cobertura integral da API.'
],say:'A API oferece contratos JSON com JWT. Compartilha o banco, mas difere da camada PHP em autenticação e regras implementadas.',question:'A assinatura do JWT esconde o payload?',answer:'Não. Ela protege integridade, não sigilo do conteúdo.'},
{id:'auditoria',group:'Banco de dados',title:'Histórico e rastreabilidade',source:'banco/tabelas/historico.php · routes/historico.js',body:[
'historico guarda instituição, tabela, ação, usuário opcional, descrição, estados anterior/novo em JSON e data. Isso ajuda a explicar mudanças. Auditoria não é backup: auditoria descreve eventos; backup permite restauração.',
'Há gravação de histórico nos fluxos PHP de refeição/cardápio e em operações da API. Não há triggers de auditoria nos scripts analisados, nem auditoria de cada baixa manual em salvar_estoque.php. Uma tabela historico não garante cobertura universal.',
'usuario_id aponta para usuarios, mas vários fluxos o deixam NULL porque operam com identidade institucional. Atribuir uma ação a uma instituição não identifica necessariamente a pessoa que a executou. A identidade dos atores poderia ser unificada numa evolução.',
'A FK institucional usa CASCADE; excluir a instituição pode remover também sua auditoria. Isso precisa ser discutido conforme retenção e domínio, não apresentado como histórico imutável.'
],say:'O histórico registra algumas mudanças, mas sua cobertura e a identificação individual do operador ainda podem melhorar.',question:'Histórico substitui backup?',answer:'Não. Ele registra eventos, enquanto backup é usado para restaurar dados.'},
{id:'migracao',group:'Banco de dados',title:'Instalação, migração e esquema efetivo',source:'banco/instalar.php · banco/migrar_integracao.php · config/conexao.php',body:[
'A conexão espera a base sistema_refeicao acessível. O instalador cria tabelas ausentes em ordem compatível com as dependências. Não recria automaticamente tabelas existentes com uma definição nova.',
'A migração só permite CLI. Usa SHOW COLUMNS antes de adicionar estoque_minimo, tema institucional, horario_id/turno_id em refeicoes e nivel administrativo. Cria configuracoes_estoque e cardapio_itens se ausentes. estoque_minimo já está no script inicial atualizado, então essa adição pode não fazer nada.',
'Verificar existência deixa a adição repetível, mas não equivale a comparar integralmente tipos, índices e constraints. Os novos IDs em refeicoes não recebem FKs. Para conhecer a instalação usada, consulte SHOW CREATE TABLE, SHOW COLUMNS e SHOW INDEX.',
'Confira PHP, mysqli, mbstring, OpenSSL, sessão, serviço do banco e permissões. Backups devem ter restauração testada em ambiente separado. O nome backup.sql não prova que o conteúdo seja um dump válido. Instalação, atualização de estrutura e restauração são operações diferentes.'
],code:'SHOW CREATE TABLE refeicoes;\nSHOW COLUMNS FROM instituicoes;\nSHOW INDEX FROM alunos;\n\n-- No terminal, não no console SQL:\n-- php banco/migrar_integracao.php',say:'Instalar cria o que falta; migrar evolui o esquema. Eu comparo o código com o banco realmente utilizado.',question:'CREATE TABLE IF NOT EXISTS acrescenta colunas novas?',answer:'Não. Uma tabela existente precisa ser alterada por migração.'},
{id:'interface',group:'Fundamentos',title:'Interface, eventos e ícones',source:'pages/estoque.php · assets/js/lucide.min.js · assets/css/',body:[
'Modais são elementos HTML cujo estado muda por classes CSS e aria-hidden. JavaScript conecta abertura, cancelamento e submit. FormData inclui campos ocultos como acao/id e fetch envia POST sem navegação imediata.',
'A interface verifica resposta.ok e texto ok, recarrega no sucesso e apresenta erro na falha. Desabilitar botão reduz cliques repetidos, mas não é idempotência do servidor. Uma garantia forte exige regra de dados ou identificação de operação.',
'Lucide transforma data-lucide em SVG. Antes era carregado por unpkg.com com @latest; a última versão usa cópia local nas cinco páginas institucionais. Isso reduz a dependência remota dos ícones, mas não torna todo o sistema offline: fontes, bibliotecas de QR e operações com servidor continuam tendo dependências.',
'localStorage guarda preferências no navegador, como tema. Há também tema no banco via migração. Estado visual local e persistência operacional não são a mesma coisa. Os arquivos de importação/download de cardápio contêm trechos demonstrativos que não implementam armazenamento completo.'
],say:'A interface organiza a experiência; servidor e banco mantêm as regras de dados. Os ícones locais resolvem uma dependência específica.',question:'Ícones locais tornam todo o sistema offline?',answer:'Não. Outras bibliotecas e o acesso ao servidor/banco mantêm suas dependências.'},
{id:'limites',group:'Defesa & qualidade',title:'Implementado, parcial e melhoria futura',source:'auth/ · pages/ · admin/ · routes/',body:[
'Há evidência de login institucional com hash, produto novo ativo, alternância de status, entrada, baixa manual com senha, refeição com histórico, cardápio com baixa transacional, consultas e API Express. Demonstre o fluxo que efetivamente usa cada implementação.',
'Limitações: baixa manual sem histórico; desconto de cardápio sem reautenticação; nenhuma unicidade de atendimento por aluno/turno/dia no endpoint apresentado; alterações Node e auditoria sem transação em vários caminhos; contagem do relatório limitada às linhas carregadas.',
'assets/js/estoque.js informa que downloads ainda não estão implementados. assets/js/relatorios.js contém dados demonstrativos. Configurações envia alterar_senha, mas salvar_cadastro.php não implementa um ramo específico dessa ação. O fluxo de recuperação por token é outro endpoint e não deve ser confundido com esse formulário.',
'Prioridades futuras: remover acesso administrativo fixo, revisar autorização da área admin, incluir proteção CSRF e limitação de tentativas, unificar validação e segredos, reforçar FKs lógicas, controlar duplicidade, auditar estoque, paginar e avaliar índices. Este guia explica essas melhorias; não as instala no sistema original.'
],say:'Reconheço limites com evidência e proponho melhorias concretas, sem apresentar recursos futuros como prontos.',question:'Como responder a uma limitação apontada pela banca?',answer:'Explicar o comportamento atual, seu impacto e uma melhoria concreta, sem afirmar que já foi implementada.'},
{id:'testes',group:'Defesa & qualidade',title:'Testes e demonstração com evidência',source:'auth/salvar_estoque.php · auth/salvar_cadastro.php',body:[
'Teste positivo verifica sucesso válido; negativo verifica rejeição; regressão verifica preservação de comportamentos após uma mudança. Mensagem na tela não basta: confira também linhas e saldos.',
'Estoque: cadastrar sem ativo, desativar, reativar, baixar com senha correta e verificar a diferença; tentar senha incorreta e conferir saldo inalterado; testar produto inativo, saldo insuficiente e outro escopo. O resultado essencial da falha é não modificar o dado.',
'Cadastro: manter sessão aberta, criar outra instituição e conferir que nome/e-mail/hash anteriores não mudaram. Testar edição explícita, e-mail duplicado e confirmação divergente. Para cardápio, induzir falha intermediária com dados fictícios e verificar rollback.',
'Concorrência precisa de duas conexões disputando o recurso; uma sequência de cliques não comprova concorrência. As correções foram testadas em tabelas temporárias PHP/MySQL e com verificações de JavaScript, mas não houve auditoria integral de todas as funcionalidades. Este site é separado e não acessa o banco operacional.'
],say:'Verifico o sucesso e, nas rejeições, a preservação do dado. Cada teste tem entrada, resultado esperado e evidência.',question:'O que verificar depois de senha incorreta na baixa?',answer:'A rejeição e a manutenção do mesmo saldo no banco.'}
]};
STUDY.flows=[
{title:'Login institucional',source:'auth/login.php',steps:[['Formulário','Enviar e-mail e senha por POST.'],['Consulta','Procurar a instituição pelo e-mail com consulta preparada.'],['Verificação','Comparar entrada e hash com password_verify.'],['Sessão','Regenerar o ID da sessão e salvar instituição.'],['Destino','Redirecionar para o dashboard.']]},
{title:'Baixa manual',source:'pages/estoque.php → auth/salvar_estoque.php',steps:[['Entrada','Enviar acao=baixa, produto, quantidade e senha.'],['Identidade','Usar a instituição da sessão e verificar sua senha.'],['Validação','Validar ID e quantidade positiva.'],['Atualização','Subtrair apenas em produto ativo, do escopo e com saldo suficiente.'],['Resposta','Conferir affected_rows e limpar senha na interface.']]},
{title:'Cardápio e ingredientes',source:'pages/salvar_cardapio.php',steps:[['Preparação','Validar campos, agregar produtos repetidos e ordenar IDs.'],['Transação','Iniciar transação e verificar turno ativo da instituição.'],['Bloqueios','SELECT FOR UPDATE nos produtos e verificação de saldo.'],['Gravação','Inserir cardápio e itens, baixar saldo e registrar histórico.'],['Conclusão','COMMIT no sucesso; ROLLBACK na falha.']]},
{title:'QR até o relatório',source:'pages/registrar_consumo.php → pages/relatorios.php',steps:[['Identificação','Ler código e selecionar turno/horário.'],['Escopo','Buscar aluno ativo por código e instituição.'],['Regras','Verificar turno e horário ativos do mesmo escopo.'],['Persistência','Inserir refeicoes e historico em transação.'],['Consulta','JOIN com alunos, filtros de instituição/data e aluno opcional.']]},
{title:'Recuperação de senha',source:'auth/enviar_recuperacao.php → auth/salvar_nova_senha.php',steps:[['Pedido','Localizar instituição pelo e-mail.'],['Token','Gerar token aleatório e salvar expiração.'],['Envio','PHPMailer envia link pela conta remetente.'],['Validação','Conferir token e prazo no banco.'],['Troca','Salvar novo hash e invalidar token.']]}
];
STUDY.defense=[
['Por que usar um banco relacional?','Entidades definidas, relacionamentos, integridade e transações. Exemplifique com aluno/refeições e cardápio/itens.','Não diga que outras tecnologias são sempre inferiores.'],
['Qual tabela centraliza o sistema?','instituicoes centraliza o escopo. Ela pode ter vários alunos e no máximo uma configuração de estoque.','administradores é separado; cardapio_itens tem vínculo indireto.'],
['Como trata duas baixas simultâneas?','Baixa manual usa UPDATE condicionado; cardápio usa transação e FOR UPDATE.','Não afirme ausência universal de deadlocks ou transações em todas as rotas.'],
['Como evita acesso a outra instituição?','Identidade vem da sessão/JWT e entra nos filtros. Validam-se também os objetos relacionados.','Reconheça diferenças e limites na área administrativa.'],
['Por que guardar hash de senha?','Permite verificar a senha sem guardar texto recuperável. PHP usa password_hash e password_verify.','Hash não é criptografia reversível e não substitui limitar tentativas.'],
['QR Code autentica o aluno?','Ele identifica um código; pode ser copiado. O operador tem sessão e o servidor valida o escopo.','Não apresente QR como prova forte de identidade.'],
['Seu banco está em terceira forma normal?','Explique dependências e separações. Há redundâncias e snapshots que precisam de justificativa.','Ter id não prova 3FN.'],
['O que acontece ao excluir uma instituição?','Várias FKs disparam CASCADE e removem dependentes, inclusive histórico.','Discuta retenção e diferença em relação à desativação.'],
['Por que dashboard e relatório podem divergir?','SUM(quantidade) e contagem de linhas não são a mesma métrica; o relatório também limita a mil linhas.','Defina filtros e significado da métrica.'],
['O que melhoraria primeiro?','Autorização admin e remoção de acesso fixo; depois consistência, auditoria e controle de duplicidade.','Priorize por risco e valor, não só por facilidade.'],
['Como provou a correção do cadastro?','Com sessão aberta, criar instituição e comparar nome/e-mail/hash da anterior; verificar o novo registro.','Mensagem de sucesso não prova preservação.'],
['Qual diferença entre API e PHP?','PHP usa sessão e gera telas; Express oferece JSON com JWT.','Não atribua à API operações que as telas executam em PHP.']
];
STUDY.bugs=[
['O produto sumiu','O registro tem saldo 15 e ativo=0. Por que não aparece?','A tela filtra ativo=1. Reativar em Configurações preserva o saldo.'],
['Atendimento duplicado','Duas linhas iguais para aluno, turno e dia. Há garantia de unicidade?','Não nesse endpoint/esquema. Defina e implemente a regra no servidor/banco.'],
['Gravação parcial na API','A refeição foi inserida e o histórico falhou. Por que a primeira persistiu?','Essas instruções não estão em transação explícita na rota. Use a mesma conexão do pool numa transação.'],
['Link no celular','O link recebido começa com localhost. Por que não abre o servidor?','localhost aponta para o próprio dispositivo que abriu o link; configure a URL acessível.'],
['Cadastro virou edição','A sessão estava aberta e o endpoint escolhia edição pela sessão.','Separe a intenção com acao=cadastrar e acao=editar_perfil.']
];
STUDY.glossary=[['SGBD','Software que gerencia banco, consultas, integridade e concorrência.'],['Entidade','Conceito do domínio, como aluno.'],['Atributo','Característica representada por coluna.'],['Registro','Uma linha da tabela.'],['PK','Chave primária única e não nula.'],['FK','Chave estrangeira que restringe referências.'],['Cardinalidade','Quantas ocorrências podem se relacionar.'],['Tabela associativa','Resolve N:N; exemplo: cardapio_itens.'],['NULL','Ausência de valor; use IS NULL.'],['Constraint','Restrição do banco, como UNIQUE e FK.'],['Índice','Estrutura auxiliar de busca, com custo em espaço e escrita.'],['Normalização','Organização de relações para reduzir redundância e anomalias.'],['Transação','Operações confirmadas ou desfeitas como unidade.'],['Commit','Confirma a transação.'],['Rollback','Desfaz alterações ainda não confirmadas.'],['Deadlock','Espera circular entre operações por bloqueios.'],['Atomicidade','Tudo ou nada para a unidade de operação.'],['JOIN','Combinação de linhas relacionadas.'],['Agregação','Resumo de linhas, como COUNT e SUM.'],['CRUD','Criar, ler, atualizar, excluir dados.'],['DDL','Definição da estrutura: CREATE, ALTER.'],['DML','Manipulação: INSERT, UPDATE, DELETE. SELECT também pode ser classificado como DQL.'],['Prepared statement','SQL parametrizado que separa estrutura e valores.'],['Hash','Transformação de sentido único usada na verificação de senhas.'],['Salt','Valor incorporado ao processamento do hash de senha para diferenciar resultados.'],['Sessão','Estado no servidor associado a um identificador do navegador.'],['JWT','Token assinado; assinatura não esconde o payload.'],['Autenticação','Verificar quem acessa.'],['Autorização','Verificar o que a identidade pode fazer.'],['CSRF','Requisição induzida usando credenciais da vítima.'],['XSS','Injeção de conteúdo executável na página.'],['SQL injection','Entrada interpretada como estrutura SQL.'],['SMTP','Protocolo de envio de e-mail.'],['TLS','Proteção do transporte com validação de certificado.'],['API','Interface de operações e contratos.'],['Endpoint','Endereço de uma operação HTTP.'],['Middleware','Processamento intermediário, como validar JWT.'],['Pool','Conjunto reutilizável de conexões.'],['Migração','Evolução controlada da estrutura.'],['Snapshot','Estado representado em determinado momento.'],['Idempotência','Repetição da operação não acrescenta efeitos além da primeira, conforme contrato.'],['DOM','Representação da página manipulada por JavaScript.'],['Fetch','API de requisições do navegador.'],['FormData','Conjunto de campos para envio de formulário.'],['InnoDB','Engine com suporte a transações e FKs usada no esquema.'],['utf8mb4','Conjunto de caracteres Unicode, incluindo caracteres de quatro bytes.']];
STUDY.sources=[['PHP: manual','https://www.php.net/manual/pt_BR/'],['PHP: hashes de senha','https://www.php.net/manual/pt_BR/function.password-hash.php'],['PHP: consultas preparadas','https://www.php.net/manual/pt_BR/mysqli.quickstart.prepared-statements.php'],['MySQL: FKs','https://dev.mysql.com/doc/refman/8.4/en/create-table-foreign-keys.html'],['MySQL: transações','https://dev.mysql.com/doc/refman/8.4/en/innodb-transaction-model.html'],['MariaDB: documentação','https://mariadb.com/docs/server'],['MDN: JavaScript','https://developer.mozilla.org/pt-BR/docs/Web/JavaScript'],['Express: roteamento','https://expressjs.com/en/guide/routing.html'],['PHPMailer','https://github.com/PHPMailer/PHPMailer'],['Lucide','https://lucide.dev/'],['sql.js: laboratório didático','https://github.com/sql-js/sql.js']];
