STUDY.quiz=[
['Qual linguagem executa as regras principais das páginas .php?',['PHP','CSS','HTML','SQL'],0,'PHP executa no servidor; SQL é usado por ele para consultar o banco.','linguagens'],
['O login institucional PHP consulta qual tabela?',['usuarios','instituicoes','administradores','alunos'],1,'A identidade institucional está em instituicoes.','identidade'],
['O que uma FOREIGN KEY garante?',['Que a senha está correta','Que a referência não nula existe','Que todo usuário pode acessar a linha','Que o saldo é positivo'],1,'Existência referencial não é autorização nem validação de saldo.','chaves'],
['Qual é o papel de cardapio_itens?',['Guardar tokens','Resolver N:N e quantidades por produto','Substituir o cadastro de alunos','Somar todos os saldos'],1,'A associação relaciona cardápios a produtos com quantidade.','chaves'],
['DECIMAL(10,2) significa:',['10 casas decimais','10 dígitos totais, 2 decimais','2 dígitos totais','Um texto de 10 caracteres'],1,'A precisão é 10 e a escala é 2.','tipos'],
['Quando DEFAULT TRUE não será usado?',['Quando ativo é omitido','Quando ativo=0 é enviado explicitamente','Quando a tabela é vazia','Quando existe um índice'],1,'Um valor explícito não é substituído pelo padrão.','tipos'],
['Qual comparação testa ausência de valor?',['= NULL','IS NULL','= 0',"= 'null'"],1,'NULL usa IS NULL ou IS NOT NULL.','tipos'],
['Qual operação preserva o produto e o saldo?',['DELETE','DROP TABLE','UPDATE ativo=0','TRUNCATE'],2,'Desativação muda um atributo, preservando a linha.','estoque'],
['COUNT(*) mede:',['A soma de quantidade','Número de linhas','Número de colunas','Saldo do estoque'],1,'COUNT conta linhas; SUM soma valores.','joins'],
['Para manter alunos sem refeições numa consulta, use:',['INNER JOIN','LEFT JOIN a partir de alunos','CROSS JOIN obrigatório','DELETE JOIN'],1,'LEFT JOIN preserva o lado esquerdo mesmo sem correspondência.','joins'],
['O que ROLLBACK faz?',['Confirma alterações','Desfaz alterações não confirmadas da transação','Apaga o banco inteiro','Reinicia o servidor'],1,'Rollback desfaz a unidade ainda não confirmada.','transacoes'],
['No cardápio, FOR UPDATE é usado para:',['Formatar a página','Bloquear as linhas lidas na transação','Criar tabela','Criptografar senha'],1,'O bloqueio coordena a leitura e a alteração concorrente do saldo.','transacoes'],
['O endpoint registrar_consumo.php grava em:',['consumo apenas','refeicoes e historico','estoque apenas','usuarios e turnos'],1,'O nome do endpoint não determina sua tabela; o SQL mostra refeicoes e historico.','qr'],
['O QR Code garante identidade forte do portador?',['Sim, por ser uma imagem','Não; identifica um código que pode ser copiado','Sim, se o aluno for ativo','Sim, se usar câmera'],1,'A leitura não substitui autenticação e regras de operação.','qr'],
['Qual é a diferença entre autenticação e autorização?',['São sinônimos','Quem acessa versus o que pode fazer','HTML versus CSS','Banco versus tabela'],1,'Uma identidade válida ainda precisa de permissão para o recurso.','identidade'],
['O que password_verify faz?',['Descriptografa a senha','Compara a entrada ao hash','Envia um e-mail','Cria um JWT'],1,'Não há recuperação da senha original a partir do hash.','recuperacao'],
['Qual credencial falhou no erro SMTP 535?',['A do aluno','A do remetente SMTP','A do produto','A chave primária'],1,'É autenticação do serviço de envio de e-mail.','recuperacao'],
['O JWT assinado mantém seu payload secreto?',['Sim','Não, assinatura protege integridade','Só quando tem ID','Sempre que expira'],1,'O payload normalmente é legível; assinatura não é criptografia.','api'],
['Criar um índice em toda coluna é sempre bom?',['Sim','Não; há custo de espaço e escrita','Sim, porque elimina validação','Sim, porque dispensa JOIN'],1,'Índices devem ser justificados por consultas e medições.','indices'],
['CREATE TABLE IF NOT EXISTS altera uma tabela antiga?',['Sim, copia todas as colunas novas','Não; precisa de migração','Só quando o nome tem acento','Só se não houver índices'],1,'A definição não é reaplicada em tabela existente.','migracao'],
['Os IDs turno_id e horario_id de refeicoes têm FKs na migração?',['Ambos têm CASCADE','Não, foram adicionados como INT NULL','Apenas horario_id','Ambos são PKs'],1,'São relações lógicas sem FK declarada nesse script.','integridade'],
['Uma instituição pode ter quantas configurações de estoque?',['Exatamente duas','Zero ou uma','Ilimitadas com mesmo instituicao_id','Sempre exatamente uma'],1,'UNIQUE limita a uma, mas não obriga a criar a linha.','chaves'],
['O erro de cadastro com sessão foi corrigido por:',['Apagar a conta antiga','Separar cadastrar e editar_perfil','Retirar a senha','Trocar MySQL por Node'],1,'A intenção da operação agora é explícita.','identidade'],
['Toda baixa de estoque grava histórico no PHP?',['Sim','Não; baixa manual não insere histórico nesse endpoint','Somente se ativo=0','Somente se usar CSS'],1,'Auditoria depende dos pontos em que INSERT no histórico é executado.','auditoria'],
['Por que a validação no servidor é necessária?',['Porque HTML não aceita números','Porque requisições podem contornar a interface','Porque CSS não tem banco','Porque PHP não executa SQL'],1,'O servidor não deve confiar em validações exclusivas do navegador.','php'],
['Uma FK de aluno e outra de instituição garantem mesmo escopo?',['Sempre','Não; as referências podem ser válidas e incompatíveis entre si','Somente com SELECT *','Somente com ativo=1'],1,'A pertença do aluno à instituição deve ser validada.','integridade'],
['O relatório atual pode limitar suas estatísticas por quê?',['LIMIT 1000 e contagem das linhas carregadas','Não usa banco','Só usa JSON','Porque tem CSS'],0,'As estatísticas são calculadas sobre o resultado limitado.','joins'],
['Qual afirmação é correta sobre a API?',['Todas as telas a utilizam','É um caminho Express separado com JWT','Substitui automaticamente a sessão PHP','Não consulta banco'],1,'A arquitetura possui duas implementações, não uma chamada automática entre elas.','arquitetura'],
['O que comprova uma rejeição de baixa?',['Apenas um alert','Erro e saldo inalterado no banco','Botão azul','A janela fechar'],1,'O estado persistido precisa continuar igual.','testes'],
['Qual afirmação sobre o projeto é honesta?',['Reduz desperdício em 50% comprovadamente','Organiza registros; impacto precisa de medição','Está livre de qualquer falha','Tem auditoria integral'],1,'Não se inventam métricas nem garantias sem avaliação.','visao']
];
STUDY.exercises=[
{title:'1. Filtrar pelo escopo',task:'Liste item e quantidade dos produtos ativos da instituição 1, ordenados por item.',hint:'Use WHERE com duas condições, e ORDER BY.',solution:'SELECT item, quantidade FROM estoque WHERE instituicao_id=1 AND ativo=1 ORDER BY item;',explain:'O filtro de instituição separa Escola Horizonte de Escola Aurora; ativo=1 retira o produto desativado.'},
{title:'2. Juntar entidades',task:'Mostre nome do aluno, tipo e data de cada refeição da instituição 1.',hint:'Associe refeicoes r a alunos a pelo aluno_id.',solution:'SELECT a.nome, r.tipo, r.data_refeicao FROM refeicoes r JOIN alunos a ON a.id=r.aluno_id WHERE r.instituicao_id=1 ORDER BY r.id;',explain:'O nome vem de alunos e o evento de refeicoes; não foi necessário repetir o cadastro.'},
{title:'3. Contar ou somar?',task:'Compare COUNT(*) e SUM(quantidade) nas refeições da instituição 1.',hint:'Você pode usar as duas agregações no mesmo SELECT.',solution:'SELECT COUNT(*) AS registros, SUM(quantidade) AS unidades FROM refeicoes WHERE instituicao_id=1;',explain:'O conjunto inicial retorna 3 registros e 4 unidades. Uma linha tem quantidade=2.'},
{title:'4. Encontrar quem não comeu',task:'Liste alunos da instituição 1 sem qualquer refeição no conjunto fictício.',hint:'Use LEFT JOIN e teste r.id IS NULL.',solution:'SELECT a.nome FROM alunos a LEFT JOIN refeicoes r ON r.aluno_id=a.id WHERE a.instituicao_id=1 AND r.id IS NULL;',explain:'Carla é preservada pelo LEFT JOIN, embora não haja correspondência em refeicoes.'},
{title:'5. Agregar por aluno',task:'Some as quantidades por aluno da instituição 1.',hint:'Agrupe pelo identificador e nome.',solution:'SELECT a.nome, SUM(r.quantidade) AS total FROM alunos a JOIN refeicoes r ON r.aluno_id=a.id WHERE a.instituicao_id=1 GROUP BY a.id,a.nome ORDER BY total DESC;',explain:'GROUP BY forma grupos; SUM resume as quantidades de cada aluno.'},
{title:'6. Baixa condicionada',task:'Desconte 3 do produto 1 apenas se for ativo, da instituição 1 e tiver saldo. Depois consulte o produto.',hint:'Faça UPDATE com condições e um SELECT para verificar.',solution:'UPDATE estoque SET quantidade=quantidade-3 WHERE id=1 AND instituicao_id=1 AND ativo=1 AND quantidade>=3; SELECT item,quantidade FROM estoque WHERE id=1;',explain:'O saldo inicial de arroz é 10 e vira 7. A simulação SQL não implementa login nem senha; essas verificações pertencem ao servidor do projeto.'},
{title:'7. Desfazer uma alteração',task:'Abra transação, desconte 2 do produto 1, faça ROLLBACK e consulte o saldo.',hint:'BEGIN; UPDATE; ROLLBACK; SELECT.',solution:'BEGIN; UPDATE estoque SET quantidade=quantidade-2 WHERE id=1; ROLLBACK; SELECT item,quantidade FROM estoque WHERE id=1;',explain:'Após rollback o saldo volta ao que era antes da transação. Reinicie a base para comparar com 10.'},
{title:'8. Ver uma FK em ação',task:'Tente inserir uma refeição para aluno 999, que não existe.',hint:'O banco didático também habilita FKs.',solution:"INSERT INTO refeicoes (id,instituicao_id,aluno_id,tipo,data_refeicao,quantidade) VALUES (99,1,999,'Almoço','2026-09-22',1);",explain:'O erro FOREIGN KEY constraint failed é o resultado esperado: a referência não existe.'},
{title:'9. Percorrer a relação N:N',task:'Mostre nome do cardápio, produto e quantidade dos itens.',hint:'Passe por cardapio_itens e associe cardapios e estoque.',solution:'SELECT c.nome AS cardapio,e.item,ci.quantidade FROM cardapio_itens ci JOIN cardapios c ON c.id=ci.cardapio_id JOIN estoque e ON e.id=ci.estoque_id ORDER BY ci.id;',explain:'A tabela intermediária permite vários produtos no cardápio e o mesmo produto em vários cardápios.'},
{title:'10. Unicidade por instituição',task:'Tente cadastrar outro aluno com codigo A001 na instituição 1.',hint:'A dupla instituicao_id,codigo é única.',solution:"INSERT INTO alunos (id,instituicao_id,nome,turma,codigo,ativo) VALUES (9,1,'Pessoa fictícia','1A','A001',1);",explain:'A restrição UNIQUE rejeita a duplicação na mesma instituição. A instituição 2 pode ter A001.'}
];
STUDY.seed=`PRAGMA foreign_keys=ON;
CREATE TABLE instituicoes(id INTEGER PRIMARY KEY,nome TEXT NOT NULL,email TEXT NOT NULL UNIQUE);
CREATE TABLE alunos(id INTEGER PRIMARY KEY,instituicao_id INTEGER NOT NULL REFERENCES instituicoes(id) ON DELETE CASCADE,nome TEXT NOT NULL,turma TEXT,codigo TEXT,ativo INTEGER DEFAULT 1,UNIQUE(instituicao_id,codigo));
CREATE TABLE estoque(id INTEGER PRIMARY KEY,instituicao_id INTEGER NOT NULL REFERENCES instituicoes(id) ON DELETE CASCADE,item TEXT NOT NULL,quantidade NUMERIC,unidade TEXT,estoque_minimo NUMERIC DEFAULT 0,ativo INTEGER DEFAULT 1);
CREATE TABLE refeicoes(id INTEGER PRIMARY KEY,instituicao_id INTEGER NOT NULL REFERENCES instituicoes(id) ON DELETE CASCADE,aluno_id INTEGER NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,tipo TEXT,data_refeicao TEXT,quantidade INTEGER DEFAULT 1);
CREATE TABLE cardapios(id INTEGER PRIMARY KEY,instituicao_id INTEGER REFERENCES instituicoes(id) ON DELETE CASCADE,nome TEXT);
CREATE TABLE cardapio_itens(id INTEGER PRIMARY KEY,cardapio_id INTEGER NOT NULL REFERENCES cardapios(id) ON DELETE CASCADE,estoque_id INTEGER NOT NULL REFERENCES estoque(id),quantidade NUMERIC);
CREATE TABLE historico(id INTEGER PRIMARY KEY,instituicao_id INTEGER REFERENCES instituicoes(id) ON DELETE CASCADE,tabela TEXT,acao TEXT,descricao TEXT);
INSERT INTO instituicoes VALUES(1,'Escola Horizonte','horizonte@example.com'),(2,'Escola Aurora','aurora@example.com');
INSERT INTO alunos VALUES(1,1,'Ana','1A','A001',1),(2,1,'Bruno','1A','A002',1),(3,1,'Carla','2B','A003',1),(4,2,'Diego','1A','A001',1);
INSERT INTO estoque VALUES(1,1,'Arroz',10,'kg',3,1),(2,1,'Feijão',5,'kg',2,1),(3,1,'Leite',8,'L',4,0),(4,2,'Arroz',20,'kg',5,1);
INSERT INTO refeicoes VALUES(1,1,1,'Almoço','2026-09-22',1),(2,1,2,'Almoço','2026-09-22',2),(3,1,1,'Lanche','2026-09-21',1),(4,2,4,'Almoço','2026-09-22',1);
INSERT INTO cardapios VALUES(1,1,'Almoço de terça');
INSERT INTO cardapio_itens VALUES(1,1,1,2),(2,1,2,1);
INSERT INTO historico VALUES(1,1,'cardapios','INSERT','Cardápio fictício para estudo');`;
STUDY.outline=[
['Abertura e problema',60,'Apresente a alimentação escolar e a necessidade de organizar registros. Diga o objetivo do sistema sem inventar impacto quantitativo.'],
['Visão do sistema',75,'Mostre os módulos e os atores. Diferencie instituição, administrador, aluno e produto.'],
['Arquitetura e linguagens',90,'Explique navegador → PHP → mysqli → banco. Apresente a API Node como caminho separado.'],
['Banco de dados',180,'Use o atlas: instituição 1:N alunos, aluno 1:N refeições, cardápio N:N estoque via itens. Explique PK, FK, UNIQUE, DECIMAL e relações lógicas sem FK.'],
['Demonstração dos fluxos',150,'Cadastre produto ativo, desative/reative, faça baixa válida e inválida. Explique QR para refeição e o cardápio transacional.'],
['Segurança e testes',90,'Mostre hash, sessão, escopo e validação. Explique como verificou que uma rejeição não alterou o saldo.'],
['Limites e conclusão',75,'Diga o que está implementado e priorize evoluções: autorização administrativa, auditoria, consistência e métricas. Termine retomando o objetivo.']
];
